version: '3.8'

services:
  # app:
  #   build: .
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:latest
    container_name: earth_ai_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=earth_ai_db
    ports:
      - "5432:5432"
    # volumes:
      # - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
